version: "3.9"
services:
  users-db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: users
    ports: ["5433:5432"]
    volumes: [ "users_db_data:/var/lib/postgresql/data" ]

  contents-db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: contents
    ports: ["5434:5432"]
    volumes: [ "contents_db_data:/var/lib/postgresql/data" ]

volumes:
  users_db_data:
  contents_db_data:
