# ---------- Build stage ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Tüm solution'ý kopyala (dockerignore ile bin/obj'yi dýþla)
COPY . .

# Restore & Publish
RUN dotnet restore "./UserService/UserService.Api.csproj"
RUN dotnet publish "./UserService/UserService.Api.csproj" -c Release -o /app /p:UseAppHost=false

# ---------- Run stage ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Uygulama çýktýsýný kopyala
COPY --from=build /app .

# HTTP ile yayýnla (HTTPS gerektirme — önce yaþadýðýmýz mount hatasýný önler)
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "UserService.Api.dll"]
